version: '3.8'

services:
  inputs_firebase_dev:
    build:
      context: ../../../
      dockerfile: infrastructure/docker/development/app/Dockerfile
      args:
        - ENVIRONMENT=development
    container_name: inputs_firebase_dev
    restart: unless-stopped
    env_file:
      - .env.development
    ports:
      - "8005:8000"
    volumes:
      - ../../../app:/usr/inputs_python/app:rw
    networks:
      - inputs_network      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  inputs_network:
    driver: bridge


